// ============================================================
// Abyssos v4.0 — Card Data
// Monster 18종 + Gatekeeper 9종 + Guardian 9종 = 총 36종
// ============================================================

/**
 * 카드 디자인 규격:
 * - 750×1050px (기존 타로와 동일한 비율)
 * - 몬스터: 어두운 배경 + 원소색 액센트 + 전투력 강조
 * - 수문장: 금박 프레임 + 보라색/검은색 + 웅장한 느낌
 * - 수호카드: 밝은 금색 + 신성한 느낌 + 효과 설명
 */

// ─── 원소별 색상 팔레트 ──────────────────────────────────────────
export const ELEMENT_COLORS = {
  ice:      { primary: '#7ec8e3', secondary: '#4a90b8', bg: '#0a1218', accent: '#b8dff0' },
  illusion: { primary: '#b088c0', secondary: '#6b4e7a', bg: '#120a15', accent: '#d4b8e0' },
  blood:    { primary: '#c0392b', secondary: '#8b1a1a', bg: '#180a0a', accent: '#e06050' },
  fire:     { primary: '#e67e22', secondary: '#b8551a', bg: '#180e05', accent: '#f0a050' },
  mud:      { primary: '#5c6b4a', secondary: '#3a4530', bg: '#0e100a', accent: '#8a9a70' },
  gold:     { primary: '#f0d060', secondary: '#b8860b', bg: '#151008', accent: '#f5e6a0' },
  poison:   { primary: '#27ae60', secondary: '#1a7040', bg: '#081208', accent: '#50d080' },
  wind:     { primary: '#9b59b6', secondary: '#6b3090', bg: '#100818', accent: '#c080e0' },
  holy:     { primary: '#f5e6a0', secondary: '#c4a040', bg: '#121008', accent: '#fff8d0' },
};

// ─── 18종 몬스터 카드 데이터 ────────────────────────────────────
// 각 층: A(하급, 칸1~5), B(상급, 칸7~11)
export const MONSTER_CARDS = [
  // ── 9층 배반 ❄️ ──
  {
    id: 'monster-9a', circleId: 9, tier: 'A', name: '얼음 망자', nameEn: 'Frost Wraith',
    element: 'ice', power: 3,
    ability: '없음', abilityEn: 'None',
    reward: 'HP +6', rewardEn: 'HP +6',
    penalty: 'HP -3', penaltyEn: 'HP -3',
    symbol: 'frost-wraith',
  },
  {
    id: 'monster-9b', circleId: 9, tier: 'B', name: '동상 골렘', nameEn: 'Cryo-Golem',
    element: 'ice', power: 6,
    ability: '빙벽: 받는 피해 -2', abilityEn: 'Ice Wall: -2 damage taken',
    reward: 'HP +14, 방어+1', rewardEn: 'HP +14, Def+1',
    penalty: 'HP -9, 1턴 스턴', penaltyEn: 'HP -9, Stun 1t',
    symbol: 'cryo-golem',
  },
  // ── 8층 사기 🎭 ──
  {
    id: 'monster-8a', circleId: 8, tier: 'A', name: '가면 악마', nameEn: 'Mask Fiend',
    element: 'illusion', power: 4,
    ability: '가면 바꾸기: D6 눈 변경 (30%)', abilityEn: 'Mask Swap: D6 reroll (30%)',
    reward: 'HP +8', rewardEn: 'HP +8',
    penalty: 'HP -5', penaltyEn: 'HP -5',
    symbol: 'mask-fiend',
  },
  {
    id: 'monster-8b', circleId: 8, tier: 'B', name: '그림자 밀매자', nameEn: 'Shadow Trafficker',
    element: 'illusion', power: 7,
    ability: '계약서: HP 5 지불 → 전투력 -2', abilityEn: 'Contract: Pay 5 HP → Power -2',
    reward: 'HP +16', rewardEn: 'HP +16',
    penalty: 'HP -10, 버프 1개 소멸', penaltyEn: 'HP -10, Lose 1 buff',
    symbol: 'shadow-trafficker',
  },
  // ── 7층 폭력 🩸 ──
  {
    id: 'monster-7a', circleId: 7, tier: 'A', name: '피의 병사', nameEn: 'Blood Soldier',
    element: 'blood', power: 4,
    ability: '없음', abilityEn: 'None',
    reward: 'HP +8', rewardEn: 'HP +8',
    penalty: 'HP -4', penaltyEn: 'HP -4',
    symbol: 'blood-soldier',
  },
  {
    id: 'monster-7b', circleId: 7, tier: 'B', name: '켄타우로스 궁수', nameEn: 'Centaur Archer',
    element: 'blood', power: 7,
    ability: '원거리 저격: 전투 전 3 데미지', abilityEn: 'Snipe: 3 pre-damage',
    reward: 'HP +18, 이동+2', rewardEn: 'HP +18, Move+2',
    penalty: 'HP -12, 2칸 후퇴', penaltyEn: 'HP -12, Back 2',
    symbol: 'centaur-archer',
  },
  // ── 6층 이단 🔥 ──
  {
    id: 'monster-6a', circleId: 6, tier: 'A', name: '불꽃 교리관', nameEn: 'Flame Dogmatist',
    element: 'fire', power: 4,
    ability: '심문 퀴즈: 정답 시 전투력 -1', abilityEn: 'Quiz: Correct → Power -1',
    reward: 'HP +10', rewardEn: 'HP +10',
    penalty: 'HP -5', penaltyEn: 'HP -5',
    symbol: 'flame-dogmatist',
  },
  {
    id: 'monster-6b', circleId: 6, tier: 'B', name: '이단 재판관', nameEn: 'Heresy Inquisitor',
    element: 'fire', power: 8,
    ability: '화형 선고: 매 턴 전투력 +1 (최대+3)', abilityEn: 'Pyre: Power +1/turn (max +3)',
    reward: 'HP +18, 버프+1턴', rewardEn: 'HP +18, Buffs +1t',
    penalty: 'HP -14, 모든 버프 소멸', penaltyEn: 'HP -14, All buffs lost',
    symbol: 'heresy-inquisitor',
  },
  // ── 5층 분노 😡 ──
  {
    id: 'monster-5a', circleId: 5, tier: 'A', name: '진흙 익사자', nameEn: 'Mud Drowner',
    element: 'mud', power: 4,
    ability: '발목 붙잡기: 패배 시 다음 D6 -1', abilityEn: 'Grasp: Lose → Next D6 -1',
    reward: 'HP +10', rewardEn: 'HP +10',
    penalty: 'HP -5, 이동-1', penaltyEn: 'HP -5, Move-1',
    symbol: 'mud-drowner',
  },
  {
    id: 'monster-5b', circleId: 5, tier: 'B', name: '스틱스 히드라', nameEn: 'Styx Hydra',
    element: 'mud', power: 8,
    ability: '재생: 패배 시 +2 강화 재대결', abilityEn: 'Regen: Lose → Rematch at +2',
    reward: 'HP +22', rewardEn: 'HP +22',
    penalty: 'HP -10 → -14(2차)', penaltyEn: 'HP -10 → -14(rematch)',
    symbol: 'styx-hydra',
  },
  // ── 4층 탐욕 💰 ──
  {
    id: 'monster-4a', circleId: 4, tier: 'A', name: '인색한 망령', nameEn: 'Miser Wraith',
    element: 'gold', power: 4,
    ability: '구두쇠: 50% 확률 무효', abilityEn: 'Miser: 50% no effect',
    reward: 'HP +10 (50%)', rewardEn: 'HP +10 (50%)',
    penalty: 'HP -5 (50%)', penaltyEn: 'HP -5 (50%)',
    symbol: 'miser-wraith',
  },
  {
    id: 'monster-4b', circleId: 4, tier: 'B', name: '황금 탐식자', nameEn: 'Gold Devourer',
    element: 'gold', power: 8,
    ability: '삼키기: 패배 시 수호카드 1장 비활성', abilityEn: 'Devour: Lose → 1 Guardian disabled',
    reward: 'HP +20', rewardEn: 'HP +20',
    penalty: 'HP -11, 수호카드 비활성', penaltyEn: 'HP -11, Guardian disabled',
    symbol: 'gold-devourer',
  },
  // ── 3층 식탐 🤢 ──
  {
    id: 'monster-3a', circleId: 3, tier: 'A', name: '악취 구더기', nameEn: 'Stench Maggot',
    element: 'poison', power: 5,
    ability: '독 안개: 전투 후 2턴 HP-2', abilityEn: 'Toxic Fog: 2t HP-2 after',
    reward: 'HP +10', rewardEn: 'HP +10',
    penalty: 'HP -5, 독 2턴', penaltyEn: 'HP -5, Poison 2t',
    symbol: 'stench-maggot',
  },
  {
    id: 'monster-3b', circleId: 3, tier: 'B', name: '식인 식물', nameEn: 'Maneater Plant',
    element: 'poison', power: 8,
    ability: '포식: 전투 전 HP-5, 승리+10', abilityEn: 'Devour: Pre-5HP, Win+10',
    reward: 'HP +20 (+추가+10)', rewardEn: 'HP +20 (+Bonus+10)',
    penalty: 'HP -12', penaltyEn: 'HP -12',
    symbol: 'maneater-plant',
  },
  // ── 2층 색욕 🌪 ──
  {
    id: 'monster-2a', circleId: 2, tier: 'A', name: '바람 망령', nameEn: 'Wind Wraith',
    element: 'wind', power: 5,
    ability: '돌풍: 전투 후 1칸 강제 전진', abilityEn: 'Gust: Force +1 tile after',
    reward: 'HP +12', rewardEn: 'HP +12',
    penalty: 'HP -6', penaltyEn: 'HP -6',
    symbol: 'wind-wraith',
  },
  {
    id: 'monster-2b', circleId: 2, tier: 'B', name: '허리케인 와이번', nameEn: 'Hurricane Wyvern',
    element: 'wind', power: 9,
    ability: '강풍: 전투 후 2칸 무작위 이동', abilityEn: 'Gale: Random 2-tile move after',
    reward: 'HP +22', rewardEn: 'HP +22',
    penalty: 'HP -14', penaltyEn: 'HP -14',
    symbol: 'hurricane-wyvern',
  },
  // ── 1층 미망 ✨ ──
  {
    id: 'monster-1a', circleId: 1, tier: 'A', name: '고대 철학자', nameEn: 'Ancient Sage',
    element: 'holy', power: 5,
    ability: '지혜의 시험: 퀴즈로 전투 대체 가능', abilityEn: 'Wisdom Test: Quiz instead of fight',
    reward: 'HP +14', rewardEn: 'HP +14',
    penalty: 'HP -5', penaltyEn: 'HP -5',
    symbol: 'ancient-sage',
  },
  {
    id: 'monster-1b', circleId: 1, tier: 'B', name: '플라톤의 이데아', nameEn: "Plato's Ideal",
    element: 'holy', power: 10,
    ability: '완전한 형상: 패배해도 진행 가능', abilityEn: 'Perfect Form: Progress even on loss',
    reward: 'HP +25', rewardEn: 'HP +25',
    penalty: 'HP -16', penaltyEn: 'HP -16',
    symbol: 'platos-ideal',
  },
];

// ─── 9종 수문장 카드 데이터 ────────────────────────────────────
export const GATEKEEPER_CARDS = [
  {
    id: 'gk-9', circleId: 9, name: '얼음 거인', nameEn: 'Ice Goliath',
    title: '코퀴토스의 파수꾼', titleEn: 'Warden of Cocytus',
    element: 'ice', power: 4,
    mechanic: '빙결의 숨결: D6 굴림 1~3이면 플레이어 D6-1',
    mechanicEn: 'Frost Breath: Roll D6, on 1-3 player D6-1',
    rewardHp: 15, rewardMove: 1, penaltyHp: 8, pushback: 2,
    guardianId: 'guardian-9',
    narrative: '루치페르의 눈물로 빚어진 얼음 거인이 관문을 막아섰다.',
    narrativeEn: "A giant of ice forged from Lucifer's tears blocks the gate.",
    symbol: 'ice-goliath',
  },
  {
    id: 'gk-8', circleId: 8, name: '위장의 군주', nameEn: 'Lord of Masks',
    title: '말레볼제의 감시자', titleEn: 'Overseer of Malebolge',
    element: 'illusion', power: 5,
    mechanic: '10개의 가면: 파워가 3~7로 무작위 변경',
    mechanicEn: '10 Masks: Power randomly changes to 3-7',
    rewardHp: 15, rewardMove: 1, penaltyHp: 9, pushback: 2,
    guardianId: 'guardian-8',
    narrative: '열 개의 얼굴을 가진 사기꾼 군주. 어느 얼굴이 진짜인가.',
    narrativeEn: 'A deceiver lord of ten faces. Which one is real?',
    symbol: 'lord-of-masks',
  },
  {
    id: 'gk-7', circleId: 7, name: '피의 파수꾼', nameEn: 'Blood Sentinel',
    title: '플레게톤의 수호자', titleEn: 'Guardian of Phlegethon',
    element: 'blood', power: 5,
    mechanic: '끓는 피의 비: D6 도전 전 HP-2 선제 피해',
    mechanicEn: 'Boiling Blood Rain: Take 2 pre-damage before D6',
    rewardHp: 18, rewardMove: 2, penaltyHp: 10, pushback: 3,
    guardianId: 'guardian-7',
    narrative: '끓는 피의 강에서 솟아오른 거대한 파수꾼.',
    narrativeEn: 'A colossal sentinel risen from the boiling blood river.',
    symbol: 'blood-sentinel',
  },
  {
    id: 'gk-6', circleId: 6, name: '불꽃 심문관', nameEn: 'Flame Inquisitor',
    title: '이단자 도시의 문지기', titleEn: 'Gatekeeper of the Heretic City',
    element: 'fire', power: 5,
    mechanic: '진리의 불꽃: 퀴즈 정답 시 D6+1, 오답 시 파워+1',
    mechanicEn: 'Flame of Truth: Quiz right→D6+1, wrong→Power+1',
    rewardHp: 18, rewardMove: 2, penaltyHp: 8, pushback: 2,
    guardianId: 'guardian-6',
    narrative: '불타는 석관의 도시에서 심문관이 당신을 심문한다.',
    narrativeEn: 'The inquisitor from the burning sepulcher city judges you.',
    symbol: 'flame-inquisitor',
  },
  {
    id: 'gk-5', circleId: 5, name: '분노의 화신', nameEn: 'Avatar of Wrath',
    title: '스틱스 늪의 지배자', titleEn: 'Master of the Styx Marsh',
    element: 'mud', power: 6,
    mechanic: '광폭화: 매 턴 파워+1(최대+3). D6=6이면 즉시 승리',
    mechanicEn: 'Enrage: Power +1/turn (max+3). D6=6 instant win',
    rewardHp: 20, rewardMove: 2, penaltyHp: 12, pushback: 3,
    guardianId: 'guardian-5',
    narrative: '스틱스 늪에서 분노가 형체를 얻어 울부짖는다.',
    narrativeEn: "Wrath itself has taken form from Styx's black marsh.",
    symbol: 'avatar-of-wrath',
  },
  {
    id: 'gk-4', circleId: 4, name: '황금 골렘', nameEn: 'Golden Golem',
    title: '탐욕의 파수꾼', titleEn: 'Sentinel of Avarice',
    element: 'gold', power: 6,
    mechanic: '황금의 무게: 보유 수호카드당 파워+1',
    mechanicEn: 'Weight of Gold: +1 Power per Guardian card held',
    rewardHp: 20, rewardMove: 3, penaltyHp: 12, pushback: 3,
    guardianId: 'guardian-4',
    narrative: '황금 바위가 살아 움직인다. 탐욕의 대가를 속삭이며.',
    narrativeEn: 'Golden boulders come alive, whispering the price of avarice.',
    symbol: 'golden-golem',
  },
  {
    id: 'gk-3', circleId: 3, name: '케르베로스', nameEn: 'Cerberus',
    title: '식탐의 문지기', titleEn: 'Gatekeeper of Gluttony',
    element: 'poison', power: 7,
    mechanic: '세 개의 머리: D6 3회 굴려 2회 이상 성공',
    mechanicEn: 'Three Heads: Roll D6 3 times, need 2+ successes',
    rewardHp: 25, rewardMove: 3, penaltyHp: 15, pushback: 3,
    guardianId: 'guardian-3',
    narrative: '하데스의 파수견 케르베로스가 세 머리로 으르렁댄다.',
    narrativeEn: "Hades' guard hound Cerberus snarls with all three heads.",
    symbol: 'cerberus',
  },
  {
    id: 'gk-2', circleId: 2, name: '폭풍의 정령', nameEn: 'Storm Wraith',
    title: '영원한 허리케인', titleEn: 'The Eternal Hurricane',
    element: 'wind', power: 7,
    mechanic: '폭풍의 눈: D6 눈이 1~2 무작위 변동',
    mechanicEn: "Storm's Eye: D6 value randomly shifts by 1-2",
    rewardHp: 25, rewardMove: 3, penaltyHp: 15, pushback: 4,
    guardianId: 'guardian-2',
    narrative: '폭풍 그 자체가 의지를 갖고 관문을 지킨다.',
    narrativeEn: 'The hurricane itself guards the gate with intent.',
    symbol: 'storm-wraith',
  },
  {
    id: 'gk-1', circleId: 1, name: '베르길리우스의 그림자', nameEn: 'Shadow of Virgil',
    title: '최종 시험관', titleEn: 'The Final Examiner',
    element: 'holy', power: 8,
    mechanic: '안내자의 시험: 보유 수호카드당 D6+1',
    mechanicEn: "Guide's Trial: +1 D6 per Guardian card held",
    rewardHp: 30, rewardMove: 5, penaltyHp: 20, pushback: 5,
    guardianId: 'guardian-1',
    narrative: '안내자였던 자가 묻는다 — "너는 지옥을 통과할 자격이 있는가?"',
    narrativeEn: 'He who was the guide asks — "Are you worthy to leave Hell?"',
    symbol: 'shadow-of-virgil',
  },
];

// ─── 9종 수호카드 데이터 ────────────────────────────────────────
export const GUARDIAN_CARDS = [
  {
    id: 'guardian-9', circleId: 9, name: '얼음 거인의 심장', nameEn: 'Heart of the Ice Goliath',
    element: 'ice', effectType: 'passive',
    mainEffect: '받는 모든 피해 -2', mainEffectEn: 'All damage taken -2',
    subEffect: '함정 피해 -50%', subEffectEn: 'Trap damage -50%',
    narrative: '얼음 거인의 심장이 그대 가슴속에서 뛰기 시작했다.',
    narrativeEn: "The Ice Goliath's heart beats within your chest.",
    symbol: 'heart-of-ice',
  },
  {
    id: 'guardian-8', circleId: 8, name: '가면술사의 비밀', nameEn: 'Secret of the Mask Caster',
    element: 'illusion', effectType: 'active',
    mainEffect: '전투 1회 스킵 가능 (1회용)', mainEffectEn: 'Skip 1 battle (one-time)',
    subEffect: '20% 확률로 적 특수능력 무효', subEffectEn: '20% negate enemy ability',
    narrative: '위장의 군주의 비밀이 그대의 것이 되었다.',
    narrativeEn: 'The secret of the Lord of Masks is now yours.',
    symbol: 'mask-secret',
  },
  {
    id: 'guardian-7', circleId: 7, name: '피의 축복', nameEn: 'Blessing of Blood',
    element: 'blood', effectType: 'passive',
    mainEffect: '전투 승리 시 초과 피해만큼 HP 회복', mainEffectEn: 'Heal excess damage on victory',
    subEffect: 'HP 30% 이하 시 D6+1', subEffectEn: 'D6+1 when HP ≤ 30%',
    narrative: '플레게톤의 피가 그대의 혈관에 스며들었다.',
    narrativeEn: "Phlegethon's blood seeps into your veins.",
    symbol: 'blood-blessing',
  },
  {
    id: 'guardian-6', circleId: 6, name: '심문관의 등불', nameEn: "Inquisitor's Lantern",
    element: 'fire', effectType: 'passive',
    mainEffect: '적의 특수 능력 전투 전 열람 가능', mainEffectEn: 'See enemy ability before battle',
    subEffect: '퀴즈/시련 성공률 +30%', subEffectEn: 'Quiz/trial success +30%',
    narrative: '심문관의 등불이 어둠 속 모든 위험을 밝힌다.',
    narrativeEn: "The inquisitor's lantern reveals all dangers in the dark.",
    symbol: 'inquisitor-lantern',
  },
  {
    id: 'guardian-5', circleId: 5, name: '분노의 투구', nameEn: 'Helm of Wrath',
    element: 'mud', effectType: 'passive',
    mainEffect: '전투 D6 +1', mainEffectEn: 'Battle D6 +1',
    subEffect: '⚠ HP 회복량 -30% (트레이드오프)', subEffectEn: '⚠ HP healing -30% (tradeoff)',
    narrative: '스틱스의 분노가 투구가 되어 그대 이마를 감싼다.',
    narrativeEn: "Styx's wrath becomes a helm upon your brow.",
    symbol: 'helm-of-wrath',
  },
  {
    id: 'guardian-4', circleId: 4, name: '황금의 날개', nameEn: 'Golden Wings',
    element: 'gold', effectType: 'active',
    mainEffect: '최대 3칸 비행 이동 (3턴 쿨다운)', mainEffectEn: 'Fly up to 3 tiles (3-turn cooldown)',
    subEffect: '이동력 +1 (영구)', subEffectEn: 'Move +1 (permanent)',
    narrative: '다이달로스도 부러워할 황금 날개가 돋았다.',
    narrativeEn: 'Golden wings that even Daedalus would envy.',
    symbol: 'golden-wings',
  },
  {
    id: 'guardian-3', circleId: 3, name: '케르베로스의 목줄', nameEn: 'Collar of Cerberus',
    element: 'poison', effectType: 'passive',
    mainEffect: '전투 D6 2회 굴려 유리한 쪽 선택', mainEffectEn: 'Roll D6 twice, pick better result',
    subEffect: '몬스터 특수능력 발동 확률 -25%', subEffectEn: 'Monster ability trigger -25%',
    narrative: '케르베로스가 그대에게 길들여졌다.',
    narrativeEn: 'Cerberus has been tamed by you.',
    symbol: 'cerberus-collar',
  },
  {
    id: 'guardian-2', circleId: 2, name: '폭풍의 은총', nameEn: 'Grace of the Storm',
    element: 'wind', effectType: 'passive',
    mainEffect: '이동 주사위 최소값 +1 (1~2→3)', mainEffectEn: 'Min dice value +1 (1-2→3)',
    subEffect: '강제 이동 완전 면역', subEffectEn: 'Immune to forced movement',
    narrative: '폭풍이 이제는 등 뒤에서 그대를 밀어줄 뿐.',
    narrativeEn: 'The storm now only pushes you forward.',
    symbol: 'storm-grace',
  },
  {
    id: 'guardian-1', circleId: 1, name: '베르길리우스의 지팡이', nameEn: 'Staff of Virgil',
    element: 'holy', effectType: 'both',
    mainEffect: '모든 수호카드 효과 50% 강화', mainEffectEn: 'All Guardian effects +50%',
    subEffect: '획득 즉시 탈출 게이트 개방', subEffectEn: 'Opens escape gate on acquisition',
    narrative: '지옥 전체를 통과한 증표. 진정한 자유가 기다린다.',
    narrativeEn: 'Proof of traversing all Hell. True freedom awaits.',
    symbol: 'staff-of-virgil',
  },
];
